default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: special_style_factory_landing_development

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV["DB_USER"] %>
